name: AntiWorldFly
main: com.hm.antiworldfly.AntiWorldFly
version: ${project.version}
author: DarkPyves
load: POSTWORLD
description: A plugin to disable flying and chosen commands when joining or playing in specific worlds.
website: https://github.com/PyvesB/AntiWorldFly
api-version: 1.13
commands:
  awf:
    description: Main AntiWorldFly command, use it to list sub-commands. 
    aliases: [antiworldfly]  
    usage: /<command>
permissions:
  antiworldfly.use:
    description: Allows to use the enable, disable, add and remove commands.
    default: false
  antiworldfly.fly:
    description: Allows to fly even if player is in a world blocked by the plugin.
    default: false  
  antiworldfly.*:
    description: Star notation of permissions, includes all of them.
    default: op
    children:
      antiworldfly.use: true
      antiworldfly.fly: true

